packages: []
allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  core-js: false
  cypress: false
  cypress-accessibility-checker: false
  esbuild: false
  sharp: false
  workerd: set this to true or false
onlyBuiltDependencies:
  - cypress
